### PR TITLE
ATLAS-4159 Update Apache Storm to 2.3.0

### PR DESCRIPTION
**Pull request by martin-g**
It comes with a newer RocksDB JNI that supports Linux ARM64

### CODE REVIEW

**Comment by martin-g** [comment]
Could someone run a PreCommit job please? Thank you!

**Comment by martin-g** [comment]
Ping!

**Comment by martin-g** [comment]
Apache Storm 2.3.0 has been released recently - http://storm.apache.org/2021/09/27/storm230-released.html.
Please let me know if you prefer this PR to upgrade to 2.3.0 instead of 2.2.0!

**Comment by ashutoshm** [comment]
Please open a PR.

**Review by ashutoshm — APPROVED** [review]

**Comment by martin-g** [comment]
> Please open a PR.

What do you mean, @ashutoshm  ?
This is a PR.

**Comment by ashutoshm** [comment]
You are right. I was thinking that you would raise a separate PR for upgrading to 2.3.0. You can instead modify this one. That will work as well.

**Comment by martin-g** [comment]
OK! I will test it first on Linux ARM64 tomorrow and if everything works I will update this PR!

**Comment by martin-g** [comment]
@ashutoshm The build passed here with Storm 2.3.0. I've updated this PR!

**Comment by ashutoshm** [comment]
We were updating our CI build for the past week.

I have started CI with this change. I will commit the change once CI passes.

**Pull request merged**
