### PR TITLE
Update entity.py remove_classification method

### PR DESCRIPTION
**Pull request by itsjoaoduque**
There was a typo in the remove_classification method where it was written formart instead of format

### CODE REVIEW

**Comment by asik03** [comment]
@pareshD-1991 @mneethiraj @rkundam @chaitali Could you please review this PR? It is just a little typo. Thank you in advance

**Review by asik03 — APPROVED** [review]
LGTM

**Comment by mneethiraj** [comment]
Thanks @itsjoaoduque  for the fix.

**Comment by asik03** [comment]
@mneethiraj thank you for the approval. Could you prepare a new version including this fix? We need to apply it to our services asap. Thank you again in advance !

**Comment by mneethiraj** [comment]
@asik03  - updated Python client library is now published - https://pypi.org/project/apache-atlas/0.0.15/. Thank you for the fix.

**Pull request merged**
